spring:
  datasource:
    url: jdbc:mysql://改成你的ip地址/ShareNote?serverTimezone=Asia/Shanghai
    username: 你的用户名
    password: 你的密码
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
